import hre from "hardhat";
import type { DeployedContractsOnChains } from "hardhat-kadena/src/utils";
import fs from "fs";
import path from "path";

/**
 * Generate deployedContracts.ts file for frontend
 */
export async function generateDeployedContractsFile(deployments: any[]) {
  const contractName: string = "YourContract";
  const deploymentsByChain: Record<number, DeployedContractsOnChains> = {};
  const deployedContracts: Record<string, any> = {};

  // Get the ABI from compilation artifacts
  const artifact = await hre.artifacts.readArtifact(contractName);

  // Create a map of deployments by chain ID for easy lookup
  for (const deployment of deployments) {
    deploymentsByChain[deployment.chain] = deployment;
  }

  // Process deployments using runOverChains for consistency
  await hre.chainweb.runOverChains(async (chainId: number) => {
    // No need for explicit chainweb chain switching, runOverChains does that for us
    console.log(`Generating deployed contract data for chain ${chainId}`);

    // Skip chains that weren't in our successful deployments
    if (!deploymentsByChain[chainId]) {
      console.log(`No deployment for chain ${chainId}, skipping verification`);
      return;
    }

    const deployment = deploymentsByChain[chainId];
    deployedContracts[hre.network.config.chainId] = {
      YourContract: {
        address: deployment.address,
        abi: artifact.abi, // Use the ABI from compilation artifacts
      },
    };
  });

  const contractsDir = path.join(__dirname, "../../nextjs/contracts");
  const filePath = path.join(contractsDir, "deployedContracts.ts");

  const fileContent = `/**
 * This file is autogenerated by Scaffold-Kadena.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = ${JSON.stringify(deployedContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(filePath, fileContent);
  console.log("✅ Generated deployedContracts.ts");
}
